WINDOW_HEIGHT = 640
WINDOW_LENGTH = 1280

TITLE_FONT = "assets/fonts/sterion-font/Sterion-BLLld.ttf"
FONT = "assets/fonts/audiowide-font/Audiowide-Regular.ttf"

PLANET_LOCATION = {
    (360, 273): ("Exoplanet HAT-P-7b","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
    (382, 295): ('Exoplanet Kepler-1625b',"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
    (371, 420): ("Exoplanet HD 209458b","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
    (1018, 107): ("Exoplanet K2-18b","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
    (396, 517): ("TRAPPIST-1 Exoplanets","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
}
